name: ray_website
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: "^1.0.0"
  page_transition: "^2.0.2"
  sprung: ^3.0.0
  font_awesome_flutter: ^9.1.0
  flutter_image_slideshow: ^0.1.1
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assest/personal.jpg
  - assest/show.jpg
  - assest/sky.png
  - assest/nature.png
  - assest/city.png
  - assest/Phone/cover.png
  - assest/background.png
  - assest/background/back.png
  - assest/background/back2.png
  - assest/background/back3.png
  - assest/background/back4.png
  - assest/background/back5.png
  - assest/background/back6.png
  - assest/background/back7.png
  - assest/background/back8.png
  - assest/background/back9.png
  - assest/background/back10.png
  - assest/background/back11.png
  - assest/background/back12.png
  - assest/background/back13.png
  - assest/background/back14.png
  - assest/background/back15.png
  - assest/background/back16.png
  - assest/background/back17.png
  - assest/background/back18.png
  - assest/background/back19.png

  - assest/background/back20.png
  - assest/background/back21.png
  - assest/background/back23.png
  - assest/background/back24.png
  - assest/background/back25.png
  - assest/background/back26.png
  - assest/background/back27.png
  - assest/background/back28.png
  - assest/background/back29.png
  - assest/background/back30.png

  - assest/background/back31.png
  - assest/background/back32.png
  - assest/background/back33.png
  - assest/background/back34.png
  - assest/background/back35.png
  - assest/background/back36.png
  - assest/background/back37.png



  - assest/mj.jpg  #https://www.scottbharris.com.au/journal/my-journey/ (reference)
  - assest/citypic/hamilton/cover.png
  - assest/citypic/jinhua/cover.png

  - assest/citypic/yunnan/cover.png
  - assest/citypic/yunnan/1.png
  - assest/citypic/yunnan/11.png
  - assest/citypic/yunnan/12.png
  - assest/citypic/yunnan/13.png
  - assest/citypic/yunnan/14.png
  - assest/citypic/yunnan/15.png
  - assest/citypic/yunnan/2.png
  - assest/citypic/yunnan/3.png
  - assest/citypic/yunnan/31.png
  - assest/citypic/yunnan/32.png
  - assest/citypic/yunnan/33.png
  - assest/citypic/yunnan/34.png
  - assest/citypic/yunnan/35.png
  - assest/citypic/yunnan/36.png
  - assest/citypic/yunnan/4.png
  - assest/citypic/yunnan/41.png
  - assest/citypic/yunnan/42.png
  - assest/citypic/yunnan/43.png
  - assest/citypic/yunnan/44.png
  - assest/citypic/yunnan/45.png
  - assest/citypic/yunnan/46.png
  - assest/citypic/yunnan/47.png
  - assest/citypic/yunnan/48.png
  - assest/citypic/yunnan/5.png
  - assest/citypic/yunnan/51.png
  - assest/citypic/yunnan/52.png
  - assest/citypic/yunnan/53.png
  - assest/citypic/yunnan/54.png
  - assest/citypic/yunnan/55.png
  - assest/citypic/yunnan/56.png
  - assest/citypic/yunnan/57.png
  - assest/citypic/yunnan/6.png
  - assest/citypic/yunnan/61.png
  - assest/citypic/yunnan/62.png
  - assest/citypic/yunnan/63.png
  - assest/citypic/yunnan/64.png
  - assest/citypic/yunnan/65.png
  - assest/citypic/jinhua/1.png
  - assest/citypic/jinhua/2.png
  - assest/citypic/jinhua/3.png
  - assest/citypic/jinhua/31.png
  - assest/citypic/jinhua/32.png
  - assest/citypic/jinhua/33.png
  - assest/citypic/jinhua/34.png
  - assest/citypic/jinhua/35.png
  - assest/citypic/jinhua/36.png
  - assest/citypic/jinhua/37.png
  - assest/citypic/jinhua/4.png
  - assest/citypic/jinhua/41.png
  - assest/citypic/jinhua/42.png
  - assest/citypic/jinhua/43.png
  - assest/citypic/jinhua/44.png
  - assest/citypic/jinhua/45.png
  - assest/citypic/jinhua/46.png
  - assest/citypic/jinhua/47.png
  - assest/citypic/jinhua/48.png
  - assest/citypic/jinhua/5.png
  - assest/citypic/jinhua/53.png
  - assest/citypic/jinhua/54.png
  - assest/citypic/jinhua/55.png
  - assest/citypic/jinhua/56.png
  - assest/citypic/jinhua/57.png
  - assest/citypic/jinhua/6.png
  - assest/citypic/jinhua/61.png
  - assest/citypic/jinhua/62.png
  - assest/citypic/jinhua/63.png
  - assest/citypic/jinhua/64.png
  - assest/citypic/jinhua/65.png
  - assest/citypic/jinhua/66.png
  - assest/citypic/jinhua/11.png
  - assest/citypic/jinhua/12.png
  - assest/citypic/jinhua/13.png
  - assest/citypic/jinhua/14.png
  - assest/citypic/jinhua/15.png
  - assest/citypic/hamilton/1.png
  - assest/citypic/hamilton/2.png
  - assest/citypic/hamilton/3.png
  - assest/citypic/hamilton/4.png
  - assest/citypic/hamilton/5.png
  - assest/citypic/hamilton/6.png
  - assest/sky/day/cover.png
  - assest/sky/day/1.png
  - assest/sky/day/2.png
  - assest/sky/day/3.png
  - assest/sky/Eve/cover.png
  - assest/sky/Eve/1.png
  - assest/sky/Eve/2.png
  - assest/sky/Eve/3.png
  - assest/sky/twilight/cover.png
  - assest/sky/twilight/1.png
  - assest/sky/twilight/2.png
  - assest/sky/twilight/3.png
  - assest/Personal Pic/1.png
  - assest/Personal Pic/1.01.png
  - assest/Personal Pic/1.02.png
  - assest/Personal Pic/1.03.png
  - assest/Personal Pic/2.png
  - assest/Personal Pic/3.png
  - assest/Personal Pic/4.png
  - assest/Personal Pic/5.png
  - assest/Personal Pic/6.png
  - assest/Personal Pic/7.png
  - assest/Personal Pic/8.png
  - assest/Personal Pic/9.png
  - assest/Personal Pic/10.png
  - assest/Personal Pic/11.png
  - assest/Personal Pic/12.png
  - assest/Personal Pic/13.png
  - assest/Personal Pic/14.png
  - assest/Personal Pic/15.png
  - assest/Personal Pic/16.png
  - assest/Personal Pic/17.png
  - assest/Personal Pic/18.png
  - assest/Personal Pic/19.png
  - assest/Personal Pic/20.png
  - assest/Personal Pic/21.png
  - assest/Personal Pic/22.png
  - assest/Personal Pic/23.png
  - assest/Personal Pic/24.png
  - assest/Personal Pic/25.png
  - assest/Personal Pic/26.png
  - assest/Personal Pic/27.png
  - assest/Personal Pic/28.png
  - assest/Personal Pic/29.png
  - assest/Personal Pic/30.png
  - assest/Personal Pic/31.png
  - assest/Personal Pic/32.png
  - assest/Personal Pic/33.png
  - assest/Personal Pic/34.png
  - assest/Personal Pic/35.png
  - assest/Personal Pic/36.png
  - assest/Personal Pic/37.png
  - assest/Personal Pic/38.png
  - assest/Personal Pic/7.1.png
  - assest/Personal Pic/12.1.png
  - assest/Personal Pic/22.1.png
  - assest/nature/waterFall/spring.png
  - assest/nature/waterFall/summer.png
  - assest/nature/waterFall/fall.png
  - assest/nature/waterFall/winter.png
  - assest/nature/lake/spring.png
  - assest/nature/lake/Summer.png
  - assest/nature/lake/Fall.png
  - assest/nature/lake/winter.png
  - assest/3Dprint/1.png
  - assest/3Dprint/2.png
  - assest/3Dprint/3.png
  - assest/3Dprint/4.png
  - assest/3Dprint/5.png
  - assest/3Dprint/6.png
  - assest/3Dprint/7.png
  - assest/3Dprint/8.png
  - assest/3Dprint/9.png
  - assest/3Dprint/10.png
  - assest/3Dprint/11.png
  - assest/3Dprint/12.png
  - assest/3Dprint/13.png
  - assest/3Dprint/14.png
  - assest/3Dprint/15.png
  - assest/3Dprint/16.png
  - assest/3Dprint/17.png
  - assest/3Dprint/18.png
  - assest/3Dprint/19.png
  - assest/3Dprint/20.png
  - assest/3Dprint/21.png
  - assest/3Dprint/22.png
  - assest/3Dprint/23.png
  - assest/3Dprint/24.png
  - assest/3Dprint/25.png
  - assest/3Dprint/26.png
  - assest/3Dprint/27.png
  - assest/3Dprint/28.png
  - assest/3Dprint/29.png
  - assest/3Dprint/30.png
  - assest/3Dprint/31.png
  - assest/poem/1.png
  - assest/poem/2.png
  - assest/poem/3.png
  - assest/poem/4.png
  - assest/poem/5.png
  - assest/3Dprint/cover/1.1.png
  - assest/3Dprint/cover/1.2.png
  - assest/3Dprint/cover/1.3.png
  - assest/3Dprint/cover/1.4.png
  - assest/3Dprint/cover/1.5.png
  - assest/teacher/teac1.png
  - assest/teacher/teac2.png
  - assest/nature/jhe/s1.png
  - assest/nature/jhe/s2.png
  - assest/nature/jhe/s3.png
  - assest/nature/jhe/s4.png
  - assest/poem/guTi/m1.png
  - assest/poem/guTi/m2.png
  - assest/poem/guTi/m3.png
  - assest/poem/guTi/m4.png
  - assest/poem/guTi/s1.png
  - assest/poem/guTi/s2.png
  - assest/poem/guTi/s3.png
  - assest/poem/guTi/s4.png
  - assest/poem/guTi/s5.png
  - assest/poem/guTi/o1.png
  - assest/poem/guTi/o2.png
  - assest/poem/guTi/o3.png
  - assest/poem/guTi/o4.png
  - assest/poem/guTi/o5.png
  - assest/poem/guTi/o6.png
  - assest/poem/guTi/o7.png
  - assest/poem/guTi/o8.png
  - assest/poem/guTi/o9.png
  - assest/poem/guTi/o10.png
  - assest/poem/guTi/o11.png
  - assest/poem/guTi/o12.png
  - assest/poem/guTi/x1.png
  - assest/poem/guTi/x2.png
  - assest/poem/guTi/x3.png
  - assest/poem/guTi/x4.png
  - assest/poem/guTi/x5.png
  - assest/poem/guTi/x6.png
  - assest/poem/guTi/x7.png
  - assest/poem/guTi/z1.png
  - assest/poem/guTi/z2.png
  - assest/poem/guTi/z3.png
  - assest/poem/guTi/z4.png
  - assest/poem/guTi/z6.png
  - assest/poem/guTi/y1.png
  - assest/poem/guTi/y2.png
  - assest/poem/guTi/y3.png
  - assest/App/E1.png
  - assest/App/E2.png
  - assest/App/E3.png
  - assest/App/E4.png
  - assest/App/E6.png
  - assest/App/E7.png
  - assest/App/E8.jpg
  - assest/App/E9.jpg
  - assest/App/s1.png
  - assest/App/s2.png
  - assest/App/s3.png
  - assest/App/s4.png
  - assest/App/s5.png
  - assest/App/s6.png
  - assest/App/t1.png
  - assest/App/t2.png
  - assest/App/t3.png
  - assest/App/t4.png
  - assest/App/t5.png
  - assest/App/t6.png
  - assest/App/t7.png
  - assest/App/F1.png
  - assest/App/F2.png
  - assest/App/F3.png
  - assest/App/F4.png
  - assest/App/F5.png
  - assest/App/O1.png
  - assest/App/O2.png
  - assest/App/O3.png
  - assest/App/O4.png
  - assest/App/O5.png
  - assest/App/O6.png
  - assest/App/G1.png
  - assest/App/G2.png
  - assest/App/G3.png
  - assest/App/G4.png
  - assest/App/G5.png






  fonts:
    - family:          show
      fonts:
      - asset:        font/SHOWG.TTF
    - family:          coms
      fonts:
      - asset:        font/comsc.TTF
    - family:          bank
      fonts:
      - asset:        font/bgothm.TTF
    - family:          nan
      fonts:
      - asset:        font/nan.TTF
    - family:          yuan
      fonts:
      - asset:        font/yuan.TTF
    - family:          sw
      fonts:
      - asset:        font/sw.TTF

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
